#define MAX_SEM_VAL      1000

enum SEM_RETURN_CODES {
  ERR_SEM_DOES_NOT_EXIST = -5,
  ERR_SEM_NOT_ELLIGIBLE,
  ERR_SEM_BAD_HANDLE,
  ERR_BAD_SEM_NAME,
  ERR_BAD_SEM_VAL,
  ERR_OUT_OF_SEM,
  SEM_OK
};
